# Default SSL Configuration (SSL enabled by default)
quarkus.http.ssl.certificate.key-store-file=
quarkus.http.ssl.certificate.key-store-password=
quarkus.http.ssl.certificate.key-store-type=

# Disable SSL if the environment variable is set to 'false'
%dev.quarkus.http.ssl=false
jmeter.home=C:/Users/sagar/Downloads/apache-jmeter-5.6.3/apache-jmeter-5.6.3