# Default SSL Configuration (SSL enabled by default)
quarkus.http.ssl.certificate.key-store-file=path/to/keystore.jks
quarkus.http.ssl.certificate.key-store-password=your-password
quarkus.http.ssl.certificate.key-store-type=JKS

# Disable SSL if the environment variable is set to 'false'
%dev.quarkus.http.ssl=false